### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3830-Fall2019/lab1-marierogers98#1]
@marierogers98 

Line 3 of the YAML should have your name

around line 171 you need the graph which can be included with something similar to:

To display the saved file as shown in Figure \@ref(fig:ig), use the `include_graphics()` function from `knitr`.^[Use the argument `dpi = 96` inside `include_graphics()`.] 

```{r, label = "ig", echo = FALSE, fig.cap = "Using `knitr::include_graphics()`"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)
```

In general, you need to surround functions with back ticks....ie `` around things that end with () such as `function()`.

The rest looks correct.

**Comment by marierogers98** [comment]
I have fixed these issues!

**Comment by alanarnholt** [comment]
@marierogers98 In the future, please put your name...ie Marie Rogers where it says "Your Name" in the YAML...rest looks fine.
